global:
  name: LF Edge Interactive Landscape
  short_name: LFEdge
  repo: State-of-the-Edge/lfedge-landscape
  website: 'https://landscape.lfedge.org'
  short_domain: landscape.lfedge.org
  company_url: 'https://lfedge.org'
  membership: LF Edge Member Company
  email: info@lfedge.org
  self: 'https://www.crunchbase.com/organization/lf-edge'
  slack_channel: T08PSQ7BQ/BGD9421N1/ulrQcJybIpqYVe4DnQheBncS
  meta:
    title: LF Edge Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@LF_Edge'
    google_site_verification: M_GmEYdzsEnvJiIcvfj7gmczKsme1N5rd9RwRD35Y98
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    companies: LF Edge Member Company
    hide_license_for_categories:
      - .ORG
twitter:
  search: landscape.lfedge.org
  url: 'https://landscape.lfedge.org'
  text: LF Edge Landscape from @LF_Edge
relation:
  label: LF Edge Relation
  url: lfedge
  values:
    - id: hosted
      label: LF Edge Projects
      children:
        - id: at_large
          label: Stage 1 At Large
          prefix: LF Edge
          tag: At Large
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Edge At Large
          big_picture_color: 'rgb(24,54,114)'
        - id: growth
          label: Stage 2 Growth
          prefix: LF Edge
          tag: Growth
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Edge Growth
          big_picture_color: 'rgb(24,54,114)'
        - id: impact
          label: Stage 3 Impact
          prefix: LF Edge
          tag: Impact
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Edge Impact
          big_picture_color: 'rgb(24,54,114)'
        - id: emeritus
          label: Stage 4 Emeritus
          prefix: LF Edge
          tag: Emeritus
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Edge Emeritus
          big_picture_color: 'rgb(24,54,114)'
    - id: company
      label: LF Edge Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: LF Edge Member Products/Projects
      tag: LF Edge Member
    - id: false
      label: Non-LF Edge Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: LF Edge
    label: Premier Member
    funding: Premier
    is_large: true
  General:
    name: LF Edge
    label: Member
    funding: General
  Associate:
    name: LF Edge
    label: Associate
    funding: Associate
  Liaison:
    name: LF Edge
    label: Liaison
    funding: Liaison
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF Edge Interactive Landscape</h1> The LF Edge landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated from a community-supported Github account. It is modeled after the <a
    href="http://landscape.cncf.io">CNCF landscape</a> and based on the same open source code.<br /><br />If you would like to contribute, please open a <a
    target="_blank" href="https://github.com/State-of-the-Edge/lfedge-landscape">pull request</a> with projects in the edge ecosystem. Please note all images
    submitted must be true SVG files, include a URL to the company's site, and a Crunchbase link.
  footer: null
ads:
  - url: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=lfedge_landscape&utm_medium=web&utm_campaign=kccncna20'
    image: /images/info1.jpg
    title: KubeCon CloudNativeCon NA 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: LF Edge Landscape
    fullscreen_header: See the interactive landscape at landscape.lfedge.org
    elements:
      - type: HorizontalCategory
        category: .ORG
        rows: 3
        width: 450
        height: 160
        top: 0
        left: 0
        color: 'rgb(87,43,10)'
        fit_width: true
      - type: HorizontalCategory
        category: Traffic Routing
        rows: 3
        width: 245
        height: 160
        top: 0
        left: 470
        color: 'rgb(103,66,18)'
        fit_width: true
      - type: HorizontalCategory
        category: Platforms
        rows: 3
        width: 1470
        height: 160
        top: 0
        left: 730
        color: 'rgb(193,83,21)'
        fit_width: true
      - type: HorizontalCategory
        category: Security
        rows: 3
        width: 250
        height: 200
        top: 180
        left: 410
        color: 'rgb(220,55,57)'
        fit_width: true
      - type: HorizontalCategory
        category: Networking
        rows: 3
        width: 250
        height: 200
        top: 180
        left: 670
        color: 'rgb(171,19,20)'
        fit_width: true
      - type: HorizontalCategory
        category: Infrastructure
        rows: 3
        width: 880
        height: 200
        top: 180
        left: 930
        color: 'rgb(111,12,52)'
        fit_width: true
      - type: HorizontalCategory
        category: Other Edge Related Software
        rows: 3
        width: 380
        height: 200
        top: 180
        left: 1820
        color: 'rgb(179,60,133)'
        fit_width: true
      - type: HorizontalCategory
        category: Hardware
        rows: 3
        width: 460
        height: 160
        top: 400
        left: 0
        color: 'rgb(171,61,221)'
        fit_width: true
      - type: HorizontalCategory
        category: Edge OEMs
        rows: 3
        width: 260
        height: 160
        top: 400
        left: 470
        color: 'rgb(80,106,224)'
        fit_width: true
      - type: HorizontalCategory
        category: Wireless & Wireline
        rows: 3
        width: 460
        height: 160
        top: 400
        left: 740
        color: 'rgb(37,81,209)'
        fit_width: true
      - type: HorizontalCategory
        category: Real Estate / Land
        rows: 3
        width: 460
        height: 160
        top: 400
        left: 1220
        color: 'rgb(19,105,73)'
        fit_width: true
      - type: HorizontalCategory
        category: Services / System Integrators
        rows: 3
        width: 510
        height: 160
        top: 400
        left: 1690
        color: 'rgb(79,121,13)'
        fit_width: true
      - type: HorizontalCategory
        category: LF Edge Member Company
        rows: 10
        width: 2200
        height: 350
        top: 580
        left: 0
        color: 'rgb(126,115,14)'
        fit_width: true
      - type: LandscapeInfo
        width: 390
        height: 200
        top: 180
        left: 0
        children:
          - type: text
            text: >
              The intent is for the Landscape to be a living document that developers, investors, vendors, researchers and others can use as a resource on the
              landscape of edge computing.
            top: 16
            left: 100
            right: 140
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 5
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.lfedge.org
            top: 96
            left: 15
            font_size: 13
          - type: image
            image: left-logo.svg
            width: 110
            right: 15
            top: 19
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 16
            top: 65
            title: LF Edge Logo
test:
  header: LF Edge Interactive Landscape
  section: Stage 2 Growth
  logo: project-eve.svg
