global:
  name: LF Edge Interactive Landscape
  short_name: LFEdge
  repo: lf-edge/lfedge-landscape
  website: 'https://landscape.lfedge.org'
  short_domain: l.lfedge.org
  company_url: 'https://lfdl.io'
  email: info@lfedge.org
  meta:
    title: LF Edge Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@LF_Edge'
    google_site_verification: GOaZHK1WLPDcnST1L70tMMWe3qNr_idDogl5SryoJq8
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    cncf_sandbox: false
    companies: LF Edge Member Company
twitter:
  search: landscape.lfedge.org
  url: 'https://landscape.lfedge.org'
  text: LF Edge Landscape from @LF_Edge
relation:
  label: LF Edge Relation
  url: lfedge
  values:
    - id: hosted
      label: LF Edge Projects
      children:
        - id: graduated
          label: Graduated LF Edge Projects
          prefix: LF Edge
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LF Edge Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: Incubating LF Edge Projects
          prefix: LF Edge
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: LF Edge Incubating
          big_picture_color: 'rgb(83, 113, 189)'
    - id: company
      label: LF Edge Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: LF Edge Member Products/Projects
      tag: LF Edge Member
    - id: false
      label: Non-LF Edge Member Products/Projects
      url: 'no'
membership:
  premier:
    name: LF Edge
    label: Premier Member
    funding: Premier
  general:
    name: LF Edge
    label: Member
    funding: General
  associate:
    name: LF Edge
    label: Member
    funding: Associate
  'false':
    funding: 'No'
home:
  header: >
    <h1>LF Edge Interactive Landscape</h1> The LF Edge landscape (<a target="_blank"
    href="images/landscape.png">png</a>, <a target="_blank" href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a
    href="http://landscape.cncf.io">CNCF</a> and the <a href="http://landscape.lfdl.io">LF Deep Learning</a> landscapes and based on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/?utm_source=lfdl_landscape&utm_medium=web&utm_campaign=kccnceu19'
    image: /images/info0.jpg
  - url: 'https://events.linuxfoundation.cn/events/kubecon-cloudnativecon-china-2019/?utm_source=lfdl_landscape&utm_medium=web&utm_campaign=kccncch19'
    image: /images/info1.jpg
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: LF Edge Landscape
    fullscreen_header: See the interactive landscape at l.lfdl.io
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 1115
      height: 730
    fullscreen_size:
      width: 1155
      height: 800
    elements:
      - type: HorizontalCategory
        category: .ORG
        rows: 3
        width: 260
        height: 160
        top: 0
        left: 0
        color: 'rgb(78,171,207)'
        fit_width: true
      - type: HorizontalCategory
        category: Traffic / Delivery
        rows: 3
        width: 260
        height: 160
        top: 0
        left: 280
        color: 'rgb(104, 145, 145)'
        fit_width: true
      - type: HorizontalCategory
        category: Traffic Routing
        rows: 3
        width: 260
        height: 160
        top: 0
        left: 560
        color: 'rgb(43, 142, 136)'
        fit_width: true
      - type: HorizontalCategory
        category: Platforms
        rows: 4
        width: 275
        height: 160
        top: 0
        left: 840
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: Infrastructure
        rows: 3
        width: 705
        height: 160
        top: 190
        left: 410
        color: 'rgb(74, 131, 104)'
        fit_width: true
      - type: HorizontalCategory
        category: Hardware
        rows: 4
        width: 260
        height: 160
        top: 380
        left: 0
        color: 'rgb(142, 209, 216)'
        fit_width: true
      - type: HorizontalCategory
        category: Connectivity 
        rows: 3
        width: 260
        height: 160
        top: 380
        left: 280
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: Real Estate
        rows: 3
        width: 260
        height: 160
        top: 380
        left: 560
        color: 'rgb(108, 135, 75)'
        fit_width: true
      - type: HorizontalCategory
        category: Supply Chain 
        rows: 4
        width: 275
        height: 160
        top: 380
        left: 840
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: LF Edge Member Company
        rows: 4
        width: 1115
        height: 160
        top: 570
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: LandscapeInfo
        width: 390
        height: 160
        top: 190
        left: 5
        children:
          - type: text
            text: >
              The intent is for the Landscape to be a living document that developers, investors, vendors, researchers and others can use as a resource on the landscape of edge computing.
            top: 20
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 15
            left: 5
            width: 90
            height: 90
          - type: title
            title: l.lfedge.org
            top: 104
            left: 19
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 20
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 60
test:
  header: LF Edge Interactive Landscape
  section: Graduated LF Edge Projects
  logo: accord-net.svg
update_server:
  ip: 147.75.39.153
  update_hour: 0
  update_minute: 30
